service: gcp-ts-upload

provider:
  name: google
  stage: dev
  runtime: nodejs10
  region: us-central1
  project: cloud-functions-256703
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions
  - serverless-plugin-typescript

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: path
